-- LUXE database schema for Supabase/PostgreSQL
create extension if not exists "pgcrypto";
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,username text unique not null,display_name text,avatar_url text,bio text,created_at timestamptz default now());
create table if not exists public.posts(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,caption text,media_url text,created_at timestamptz default now());
create table if not exists public.likes(user_id uuid references public.profiles(id) on delete cascade,post_id uuid references public.posts(id) on delete cascade,created_at timestamptz default now(),primary key(user_id,post_id));
create table if not exists public.comments(id uuid primary key default gen_random_uuid(),post_id uuid references public.posts(id) on delete cascade,user_id uuid references public.profiles(id) on delete cascade,body text not null,created_at timestamptz default now());
create table if not exists public.bookmarks(user_id uuid references public.profiles(id) on delete cascade,post_id uuid references public.posts(id) on delete cascade,created_at timestamptz default now(),primary key(user_id,post_id));
create table if not exists public.follows(follower_id uuid references public.profiles(id) on delete cascade,following_id uuid references public.profiles(id) on delete cascade,created_at timestamptz default now(),primary key(follower_id,following_id),check(follower_id<>following_id));
create table if not exists public.notifications(id uuid primary key default gen_random_uuid(),user_id uuid references public.profiles(id) on delete cascade,actor_id uuid references public.profiles(id) on delete cascade,type text not null,post_id uuid references public.posts(id) on delete cascade,read boolean default false,created_at timestamptz default now());
alter table public.profiles enable row level security; alter table public.posts enable row level security; alter table public.likes enable row level security; alter table public.comments enable row level security; alter table public.bookmarks enable row level security; alter table public.follows enable row level security; alter table public.notifications enable row level security;
create policy "profiles readable" on public.profiles for select using(true); create policy "own profile" on public.profiles for all using(auth.uid()=id) with check(auth.uid()=id);
create policy "posts readable" on public.posts for select using(true); create policy "own posts" on public.posts for insert with check(auth.uid()=user_id); create policy "own posts update" on public.posts for update using(auth.uid()=user_id); create policy "own posts delete" on public.posts for delete using(auth.uid()=user_id);
create policy "likes readable" on public.likes for select using(true); create policy "own likes" on public.likes for insert with check(auth.uid()=user_id); create policy "delete own likes" on public.likes for delete using(auth.uid()=user_id);
create policy "comments readable" on public.comments for select using(true); create policy "own comments" on public.comments for insert with check(auth.uid()=user_id); create policy "own comments delete" on public.comments for delete using(auth.uid()=user_id);
create policy "own bookmarks" on public.bookmarks for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "follows readable" on public.follows for select using(true); create policy "own follows" on public.follows for insert with check(auth.uid()=follower_id); create policy "delete own follows" on public.follows for delete using(auth.uid()=follower_id);
create policy "own notifications" on public.notifications for select using(auth.uid()=user_id); create policy "notification insert" on public.notifications for insert with check(auth.uid()=actor_id);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,username,display_name) values(new.id,split_part(new.email,'@',1),split_part(new.email,'@',1)); return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
