import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Heart,MessageCircle,Plus,Search,User,Home,Bookmark,LogOut} from 'lucide-react';
import {supabase} from './supabase';
import './style.css';

const demo=[
 {id:1,user:'LUXE Studio',handle:'@luxe',text:'به دنیای LUXE خوش آمدید.',image:'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=80',likes:128},
 {id:2,user:'Aydin',handle:'@aydin',text:'طراحی، الهام و سبک زندگی در یک فضا.',image:'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&q=80',likes:94}
];
function App(){
 const [session,setSession]=useState(null),[posts,setPosts]=useState(demo),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[auth,setAuth]=useState('login'),[loading,setLoading]=useState(false),[tab,setTab]=useState('home');
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setSession(data.session));const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 async function submit(e){e.preventDefault();if(!supabase)return alert('ابتدا فایل .env را با اطلاعات Supabase تنظیم کنید.');setLoading(true);let r=auth==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});setLoading(false);if(r.error)alert(r.error.message)}
 async function logout(){await supabase?.auth.signOut();setSession(null)}
 async function like(id){setPosts(p=>p.map(x=>x.id===id?{...x,likes:x.likes+1}:x)); if(supabase&&session) await supabase.from('likes').upsert({post_id:id,user_id:session.user.id})}
 if(!session)return <main className="auth"><div className="brand">LUXE</div><p>شبکه اجتماعی طراحی‌شده برای اشتراک‌گذاری سبک، ایده و تجربه.</p><form onSubmit={submit}><input type="email" placeholder="ایمیل" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="رمز عبور" value={password} onChange={e=>setPassword(e.target.value)} required/><button disabled={loading}>{loading?'در حال ورود...':auth==='login'?'ورود':'ساخت حساب'}</button></form><button className="ghost" onClick={()=>setAuth(auth==='login'?'signup':'login')}>{auth==='login'?'حساب ندارید؟ ثبت‌نام':'حساب دارید؟ ورود'}</button></main>
 return <div className="app"><header><div className="logo">LUXE</div><div className="search"><Search size={18}/><input placeholder="جستجو..."/></div><button className="icon" onClick={logout}><LogOut size={19}/></button></header><div className="layout"><aside><Nav icon={<Home/>} text="خانه" active={tab==='home'} onClick={()=>setTab('home')}/><Nav icon={<Search/>} text="کاوش" active={tab==='explore'} onClick={()=>setTab('explore')}/><Nav icon={<Bookmark/>} text="ذخیره‌ها" active={tab==='saved'} onClick={()=>setTab('saved')}/><Nav icon={<User/>} text="پروفایل" active={tab==='profile'} onClick={()=>setTab('profile')}/><button className="new"><Plus size={18}/> انتشار</button></aside><section className="feed">{tab==='home'&&<><div className="stories"><div className="story add"><Plus/></div><div className="story">L</div><div className="story">A</div><div className="story">S</div></div>{posts.map(p=><article className="post" key={p.id}><div className="posthead"><div className="avatar">{p.user[0]}</div><div><b>{p.user}</b><small>{p.handle}</small></div></div><p>{p.text}</p><img src={p.image}/><div className="actions"><button onClick={()=>like(p.id)}><Heart size={21}/> {p.likes}</button><button><MessageCircle size={21}/> نظر</button><button><Bookmark size={21}/> ذخیره</button></div></article>)}</>}{tab!=='home'&&<div className="empty"><h2>{tab==='explore'?'کاوش':tab==='saved'?'ذخیره‌ها':'پروفایل'}</h2><p>این بخش آماده اتصال به داده‌های واقعی LUXE است.</p></div>}</section></div><nav className="mobileNav"><Nav icon={<Home/>} active={tab==='home'} onClick={()=>setTab('home')}/><Nav icon={<Search/>} active={tab==='explore'} onClick={()=>setTab('explore')}/><Nav icon={<Plus/>} active={false}/><Nav icon={<Bookmark/>} active={tab==='saved'} onClick={()=>setTab('saved')}/><Nav icon={<User/>} active={tab==='profile'} onClick={()=>setTab('profile')}/></nav></div>}
function Nav({icon,text,active,onClick}){return <button className={'nav '+(active?'active':'')} onClick={onClick}>{icon}{text&&<span>{text}</span>}</button>}
createRoot(document.getElementById('root')).render(<App/>);
